# Generated by Django 3.2.13 on 2022-06-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
    ]
